version: "3.2"
services:
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
  server:
    image: ecojuntak/chart-viewer-server:latest
    ports: 
      - 9999:9999
    links: 
      - redis:redis
    environment:
      HT_HOST: 0.0.0.0
      HT_PORT: 9999
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHART_REPOS: ${CHART_REPOS}
  ui:
    build: 
      context: ui/
      args:
        - VUE_APP_API_SERVER_HOST=http://localhost:9999
    ports: 
      - 8080:80