version: "3.2"
services:
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
  server:
    image: ecojuntak/chart-viewer:latest
    ports:
      - 9999:9999
    links:
      - redis:redis
    environment:
      HT_HOST: 0.0.0.0
      HT_PORT: 9999
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command:
      - /app/chart-viewer
      - serve
      - --redis-host
      - redis
