version: "3.2"
services:
  redis:
    image: redis:latest
    ports: 
      - 6379:6379
  server:
    image: ecojuntak/chart-viewer:latest
    ports:
      - 9999:9999
    links:
      - redis:redis
    command:
      - /app/chart-viewer
      - serve
      - --redis-host
      - redis
